export default {
  CREATE_MOVIE: 'CREATE_MOVIE',
  CREATE_MOVIE_ERROR: 'CREATE_MOVIE_ERROR',
  UPDATE_MOVIE: 'UPDATE_MOVIE',
  UPDATE_MOVIE_ERROR: 'UPDATE_MOVIE_ERROR',
  DELETE_MOVIE: 'DELETE_MOVIE',
  DELETE_MOVIE_ERROR: 'DELETE_MOVIE_ERROR',
  IS_LOADING: 'IS_LOADING',
};
